# Generated by Django 3.1.2 on 2020-11-07 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='compelete',
            new_name='complete',
        ),
    ]
